name: cleo

on:
  push:
    paths:
    - 'docker/dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: set release date
      run: | 
        echo "DATE=$(date +"%Y%m%d")" >> ${GITHUB_ENV}
    - uses: actions/checkout@v3
      name: Check out code
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: archfx/cleo
        tags: latest, $DATE
        registry: docker.io
        dockerfile: docker/dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
